### ISSUE TITLE
How to handle: rename DB/collection, change field value/type

### ISSUE THREAD

**Issue by peteh02** [ozwolf-software/mongo-trek#1]
Hi all,

I'd like to say thank you for the great work first!

I have a question regarding three specific migration steps with mongo-trek.

I'm able to map most of my required migration steps to the MongoDB database commands. However, I came up with three use cases, where I'm not sure how to proceed best with mongo-trek.

* **Renaming a database**

Is this possible with mongo-trek? 

Basically, renaming a database is quite tricky; it requires
```
db.copyDatabase('old_name', 'new_name');
use old_name
db.dropDatabase();
```

* **Renaming a collection**

The command '_renameCollection_' has to be executed against the '_admin_' DB, which requires a specific handling for such migration steps as typically all change sets won't be executed against the '_admin_' DB.

* **Change the type or value of a field in a collection**

This would be easily achievable by getting the result of the command (which is a cursor), appending it with a _forEach( function(x) { ... } )_. Can I get a cursor handle with mongo-trek (e.g. when executing the _find()_ command) or is this currently not possible? Currently, I implemented a workaround (hack), which looks like this:

```
- version: 0.0.0
    description: Change type or value of a field (key) for all entities
    author: Author
    command: {
        aggregate: "COLLECTION_NAME",
        pipeline: [
          {
            $project: { "FIELD": EXEC, ALL_OTHER_FIELDS: 1 }
            # EXEC 
            #   { $concat: ["$name", "_1"] } -> Change value based on current value
            #   { parseInt("$name") }        -> Simply change the type
          },
          {
            $out: "COLLECTION_NAME"  
          },        
        ]
    }
```

However, this has two major drawbacks:
(1) _$project_ requires all projected fields to be listed
(2) the projected collection is copied, the orginal collection is overwritten

Is there a simpler way to handle the addressed migration steps?

Kind regards,
Peter

**Comment by OzWolf** [comment]
To address your questions:

**Renaming a Database**

Not really possible because mongoTrek expects to be connected to the schema it's migrating and the driver does not follow the `use` CLI command, which means a copy-and-drop would immediately crash the process (though the `copydb` and `dropDatabase` commands need to be run from the `admin` schema anyway).

**Renaming a Collection**

This is possible using the [Aggregate Command](https://docs.mongodb.com/manual/reference/command/aggregate/#dbcmd.aggregate) and the [Drop Command](https://docs.mongodb.com/manual/reference/command/drop/#dbcmd.drop).

```yaml
migrations:
    - version: 1.0.0
      description: Copy items into new collection
      command: {
        aggregate: "items",
        pipeline: [
          { $out: "items_copy" }
        ]
      }
    - version: 1.0.1
      description: Drop old collection
      command: { drop: "items" }
```

**Change Type in Collection**

The simplest approach has no database command equivalent:

```javascript
db.getCollection("items").find().snapshot().forEach(function(d) {
    d.value = Number(d.value);
    db.getCollection("items").save(d);
});
```

But this scripting option isn't available with direct client driver calls and isn't available in the database commands framework.  So it's up to mapReduce and aggregate commands to do the job.

The aggregate function has no ability to do type conversion in Mongo, so it needs to be a combo of mapReduce into a temp collection then an aggregation back into the original.

Pre-MongoDB 3.4, this required a full property projection to write the documents back, but in Mongo 3.4, they added the `$replaceRoot` pipeline instruction.  Here's how you could do a type conversion in three migration commands in 3.4 (note for pre-3.4, the `$replaceRoot` instruction would need to be replaced with a direct field extraction):

```yaml
migrations:
  - version: 1.0.0
    description: Convert value data type into working collection
    command: {
      mapReduce: "items",
      map: "function() {
        this.value = Number(this.value);
        emit(this._id, this);
      }",
      reduce: "function(id, doc) { return doc; }",
      out: "items_work"
    }
  - version: 1.0.1
    description: Bring type-converted items back to collection
    command: {
      aggregate: "items_work",
      pipeline: [
        { $replaceRoot: { newRoot: "$value" } },
        { $out: "items" }
      ]
    }
  - version: 1.0.2
    description: Remove type-converted work collection
    command: { drop: "items_work" }
```
